
CREATE TABLE %s.GRUPO (
	AUTOID BIGSERIAL NOT NULL,
	ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(250),
	VERSION BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE %s.CONFIGURACAO_APLICACAO (
	AUTOID SMALLINT NOT NULL,
	API_KEY VARCHAR(256) NOT NULL,
	UPDATED_VERSION VARCHAR(10)
);

CREATE TABLE %s.CONFIGURACAO_EMAIL (
	AUTOID SMALLINT NOT NULL,
	HOST VARCHAR(256),
	PORT INT NOT NULL,
	USERNAME VARCHAR(100),
	PASSWORD VARCHAR(100),
	FROM VARCHAR(100),
	TLS BOOLEAN NOT NULL DEFAULT TRUE,
	AUTHENTICATION BOOLEAN NOT NULL DEFAULT TRUE,
	VERSION BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE %s.CONFIGURACAO_WEBSERVICE (
	AUTOID SMALLINT NOT NULL,
	DADO_ASSISTENCIAL_URL VARCHAR(256) NOT NULL,
	DADO_ASSISTENCIAL_DIA_CONSULTA SMALLINT NOT NULL,
	DADO_ASSISTENCIAL_DIA_ATUAL BOOLEAN NOT NULL DEFAULT FALSE,
	DADO_ASSISTENCIAL_USUARIO VARCHAR(50),
	DADO_ASSISTENCIAL_SENHA VARCHAR(100),
	DADO_ASSISTENCIAL_AGENDAMENTO BOOLEAN NOT NULL DEFAULT FALSE,
	DADO_ASSISTENCIAL_AGENDAMENTO_HORA TIME WITHOUT TIME ZONE NOT NULL,
	DADO_ASSISTENCIAL_AGENDAMENTO_HOSTNAME VARCHAR(50),
	DADO_ASSISTENCIAL_AGENDAMENTO_MAC VARCHAR(17),
	VERSION BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE %s.LOG (
	AUTOID BIGSERIAL NOT NULL,
	ESQUEMA VARCHAR(100) NOT NULL,
	TABELA VARCHAR(256) NOT NULL,
	IDENTIFICADOR VARCHAR(256) NOT NULL,
	ACAO VARCHAR(1) NOT NULL,
	ANTERIOR VARCHAR,
	NOVO VARCHAR,
	CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_USER BIGINT NOT NULL
);

CREATE TABLE %s.LOG_ACAO (
	CODIGO VARCHAR(1) NOT NULL,
	TERMO VARCHAR(10) NOT NULL
);

CREATE TABLE %s.ESTADO ( 
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(50) NOT NULL,
	SIGLA VARCHAR(2) NOT NULL
);

CREATE TABLE %s.PERMISSAO (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(100) NOT NULL,
	PERMISSAO_PAI SMALLINT,
	SEQUENCIA INT NOT NULL
);

CREATE TABLE %s.PERFIL (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(250),
	VERSION BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE %s.PERFIL_PERMISSAO (
	PERFIL BIGINT NOT NULL,
	PERMISSAO SMALLINT NOT NULL
);

CREATE TABLE %s.USUARIO (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	ROOT BOOLEAN NOT NULL DEFAULT FALSE,
	ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
	LOGIN VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	NOME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(200) NOT NULL,
	TENTATIVA SMALLINT,
	BLOQUEIO_TEMPORARIO TIMESTAMP WITHOUT TIME ZONE,
	PERFIL BIGINT NOT NULL,
	CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	VERSION BIGINT NOT NULL DEFAULT 1,
	INSTITUICAO BIGINT,
	HOSPITAL BIGINT,
	MEDICO BIGINT,
	API_KEY VARCHAR(60)
);

CREATE TABLE %s.USUARIO_ACESSO (
	AUTOID BIGSERIAL NOT NULL,
	USUARIO BIGINT NOT NULL,
	STATUS INT NOT NULL,
	MESSAGE VARCHAR NOT NULL,
	REMOTE_ADDRESS VARCHAR(50),
	REMOTE_HOST VARCHAR(50),
	USER_AGENT VARCHAR(255),
	CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE %s.SITUACAO_INTERNACAO (
	CODIGO INT NOT NULL,
	TERMO VARCHAR(100) NOT NULL
);

CREATE TABLE %s.CARATER_INTERNACAO (
	CODIGO INT NOT NULL,
	TERMO VARCHAR(100) NOT NULL
);

CREATE TABLE %s.CONDICAO_ALTA (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(100) NOT NULL
);

CREATE TABLE %s.CONDICAO_ALTA_CTI (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(150) NOT NULL
);

CREATE TABLE %s.HOSPITAL_INTERNACAO_ANTERIOR (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(100) NOT NULL
);

CREATE TABLE %s.PROCEDENCIA (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(100) NOT NULL
);

CREATE TABLE %s.MODALIDADE_INTERNACAO (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.VENTILACAO_MECANICA_TOTAL_HORAS (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.CID (
	CODIGO VARCHAR(15) NOT NULL,
	TERMO VARCHAR(300) NOT NULL
);

CREATE TABLE %s.SEXO (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.ATUACAO_MEDICA (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.RISCO_READMISSAO (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(20) NOT NULL
);

CREATE TABLE %s.CODIGO_DRG (
	CODIGO VARCHAR(5) NOT NULL,
	TERMO VARCHAR(300) NOT NULL,
	BAIXO_RISCO BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE %s.TIPO_DRG (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.MDC (
	CODIGO VARCHAR(5) NOT NULL,
	TERMO VARCHAR(200) NOT NULL
);

CREATE TABLE %s.SUPORTE_VENTILATORIO_TIPO (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.SUPORTE_VENTILATORIO_TIPO_INVASIVO (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.SUPORTE_VENTILATORIO_LOCAL (
	CODIGO CHAR(1) NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.PROCEDIMENTO (
	AUTOID BIGSERIAL NOT NULL,
	CODIGO VARCHAR(20) NOT NULL,
	NOME VARCHAR(300) NOT NULL
);

CREATE TABLE %s.ESPECIALIDADE (
	AUTOID BIGSERIAL NOT NULL,
	NOME VARCHAR(120) NOT NULL
);

CREATE TABLE %s.HOSPITAL (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	CODIGO VARCHAR(15) NOT NULL,
	NOME VARCHAR(120) NOT NULL
);

CREATE TABLE %s.INSTITUICAO (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	CODIGO VARCHAR(15) NOT NULL,
	NOME VARCHAR(120) NOT NULL
);

CREATE TABLE %s.BENEFICIARIO (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	CODIGO_PACIENTE VARCHAR(40) NOT NULL,
	NOME VARCHAR(120) NOT NULL,
	DATA_NASCIMENTO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	RECEM_NASCIDO BOOLEAN,
	PARTICULAR BOOLEAN,
	IDADE_EM_ANOS INT,
	IDADE_EM_MESES INT,
	IDADE_EM_DIAS INT,
	FAIXA_ETARIA INT
);

CREATE TABLE %s.MEDICO (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	NOME VARCHAR(300) NOT NULL,
	UF SMALLINT NOT NULL,
	CRM VARCHAR(20) NOT NULL
);

CREATE TABLE %s.MEDICO_ESPECIALIDADE (
	AUTOID BIGSERIAL NOT NULL,
	MEDICO BIGINT NOT NULL,
	ESPECIALIDADE BIGINT NOT NULL
);

CREATE TABLE %s.INTERNACAO (
	AUTOID BIGSERIAL NOT NULL,
	INSTITUICAO BIGINT NOT NULL,
	ID_EXTERNO VARCHAR(15) NOT NULL,	
	BENEFICIARIO BIGINT NOT NULL,
	SITUACAO INT,
	CARATER_INTERNACAO INT,
	NUMERO_OPERADORA VARCHAR(25),
	NUMERO_REGISTRO VARCHAR(25),
	NUMERO_ATENDIMENTO VARCHAR(25),
	NUMERO_AUTORIZACAO VARCHAR(25),
	DATA_INTERNACAO TIMESTAMP WITHOUT TIME ZONE,
	DATA_ALTA TIMESTAMP WITHOUT TIME ZONE,
	CONDICAO_ALTA CHAR(1),
	DATA_AUTORIZACAO TIMESTAMP WITHOUT TIME ZONE,
	INTERNADO_OUTRAS_VEZES BOOLEAN,
	HOSPITAL_INTERNACAO_ANTERIOR CHAR(1),
	REINTERNACAO BOOLEAN,
	RECAIDA BOOLEAN,
	ORIGEM_READMISSAO_30_DIAS VARCHAR(30),
	DATA_PREVISTA_ALTA TIMESTAMP WITHOUT TIME ZONE,
	PERMANENCIA_PREVISTA_INTERNACAO NUMERIC(7,1),
	PERMANENCIA_PREVISTA_ALTA NUMERIC(7,1),
	PERMANENCIA_REAL NUMERIC(7,1),
	PERCENTIL VARCHAR(20),
	PROCEDENCIA CHAR(1),
	MODALIDADE_INTERNACAO CHAR(1),
	VENTILACAO_MECANICA BOOLEAN,
	TOTAL_HORAS_VENTILACAO_MECANICA CHAR(1),
	PERCENTIL_10_AMERICANO NUMERIC(7,1),
	PERCENTIL_25_AMERICANO NUMERIC(7,1),
	PERCENTIL_50_AMERICANO NUMERIC(7,1),
	PERCENTIL_75_AMERICANO NUMERIC(7,1),
	PERCENTIL_90_AMERICANO NUMERIC(7,1),
	PERCENTIL_10_BRASILEIRO NUMERIC(7,1),
	PERCENTIL_25_BRASILEIRO NUMERIC(7,1),
	PERCENTIL_50_BRASILEIRO NUMERIC(7,1),
	PERCENTIL_75_BRASILEIRO NUMERIC(7,1),
	PERCENTIL_90_BRASILEIRO NUMERIC(7,1),
	PERCENTIL_10_BRASILEIRO_SEM_COND_ADQ NUMERIC(7,1),
	PERCENTIL_25_BRASILEIRO_SEM_COND_ADQ NUMERIC(7,1),
	PERCENTIL_50_BRASILEIRO_SEM_COND_ADQ NUMERIC(7,1),
	PERCENTIL_75_BRASILEIRO_SEM_COND_ADQ NUMERIC(7,1),
	PERCENTIL_90_BRASILEIRO_SEM_COND_ADQ NUMERIC(7,1),
	DATA_CADASTRO TIMESTAMP WITHOUT TIME ZONE,
	USUARIO_CADASTRO VARCHAR(20),
	DATA_CADASTRO_ALTA TIMESTAMP WITHOUT TIME ZONE,
	USUARIO_CADASTRO_ALTA VARCHAR(20),
	DATA_ULTIMA_ALTERACAO TIMESTAMP WITHOUT TIME ZONE,
	USUARIO_ULTIMA_ALTERACAO VARCHAR(20),
	CORRECAO_REGISTRO BOOLEAN,
	USUARIO_CORRECAO VARCHAR(20),
	DATA_ULTIMO_RECALCULO TIMESTAMP WITHOUT TIME ZONE,
	RISCO_READMISSAO CHAR(1),
	LEITO VARCHAR(50),	
	CID_PRINCIPAL BIGINT,
	HOSPITAL BIGINT,	
	DRG_BRASIL BIGINT,
	XML VARCHAR NOT NULL,
	CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	POPULACAO INT
);

CREATE TABLE %s.INTERNACAO_MEDICO (
	AUTOID BIGSERIAL NOT NULL,
	INTERNACAO BIGINT NOT NULL,
	MEDICO BIGINT NOT NULL,
	ESPECIALIDADE BIGINT,
	RESPONSAVEL BOOLEAN,
	ATUACAO CHAR(1)
);

CREATE TABLE %s.INTERNACAO_CID_PRINCIPAL (
	AUTOID BIGSERIAL NOT NULL,
	CID VARCHAR(15) NOT NULL,
	SENSIVEL_CUIDADO_PRIMARIO BOOLEAN
);

CREATE TABLE %s.INTERNACAO_CID_SECUNDARIO (
	AUTOID BIGSERIAL NOT NULL,
	INTERNACAO BIGINT NOT NULL,
	CID VARCHAR(15) NOT NULL
);

CREATE TABLE %s.INTERNACAO_DRG_REFINADO (
	AUTOID BIGSERIAL NOT NULL,
	CODIGO VARCHAR(20) NOT NULL,
	PERMANENCIA_PREVISTA_INTERNACAO NUMERIC(7,1),
	PERMANENCIA_PREVISTA_ALTA NUMERIC(7,1)
);

CREATE TABLE %s.INTERNACAO_DRG_BRASIL (
	AUTOID BIGSERIAL NOT NULL,
	CODIGO_DRG VARCHAR(5) NOT NULL,
	TIPO_DRG CHAR(1),
	PESO NUMERIC(14,4),
	MDC VARCHAR(5),
	DRG_REFINADO BIGINT
);

CREATE TABLE %s.INTERNACAO_PROCEDIMENTO (
	AUTOID BIGSERIAL NOT NULL,
	INTERNACAO BIGINT NOT NULL,
	PROCEDIMENTO BIGINT NOT NULL,
	PORTE VARCHAR(5),
	DATA_AUTORIZACAO TIMESTAMP WITHOUT TIME ZONE,
	DATA_SOLICITACAO TIMESTAMP WITHOUT TIME ZONE,
	DATA_EXECUCAO TIMESTAMP WITHOUT TIME ZONE,
	DATA_FINAL_EXECUCAO TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE %s.INTERNACAO_PROCEDIMENTO_MEDICO (
	AUTOID BIGSERIAL NOT NULL,
	PROCEDIMENTO BIGINT NOT NULL,
	MEDICO BIGINT NOT NULL,
	ESPECIALIDADE BIGINT
);

CREATE TABLE %s.INTERNACAO_CTI (
	AUTOID BIGSERIAL NOT NULL,
	INTERNACAO BIGINT,
	DATA_INICIAL_INTERNACAO TIMESTAMP WITHOUT TIME ZONE,
	DATA_FINAL_INTERNACAO TIMESTAMP WITHOUT TIME ZONE,
	CONDICAO_ALTA CHAR(1),
	PERMANENCIA_PREVISTA_ALTA NUMERIC(7,1),
	PERMANENCIA_REAL NUMERIC(7,1),
	LEITO VARCHAR(50),
	TIPO_CTI VARCHAR(120),
	MEDICO BIGINT,
	ESPECIALIDADE BIGINT,
	HOSPITAL BIGINT,
	CID_PRINCIPAL BIGINT,
	DRG_BRASIL BIGINT
);

CREATE TABLE %s.INTERNACAO_RECEM_NASCIDO (
	AUTOID BIGSERIAL NOT NULL,
	INTERNACAO BIGINT NOT NULL,
	PESO_NASCIMENTO INT,
	IDADE_GESTACIONAL NUMERIC(4,1),
	COMPRIMENTO NUMERIC(4,1),
	SEXO CHAR(1),
	NASCIDO_VIVO BOOLEAN,
	TOCOTRAUMATISMO BOOLEAN,
	APGAR BOOLEAN,
	APGAR_QUINTO_MINUTO INT,
	ALTA_48_HORAS BOOLEAN
);

CREATE TABLE %s.INTERNACAO_CONDICAO_ADQUIRIDA (
	AUTOID BIGSERIAL NOT NULL,
	INTERNACAO BIGINT,
	CID VARCHAR(15),
	DATA_OCORRENCIA TIMESTAMP WITHOUT TIME ZONE,
	MEDICO BIGINT,
	ESPECIALIDADE BIGINT
);

CREATE TABLE %s.INTERNACAO_ALTA_ADMINISTRATIVA (
	AUTOID BIGSERIAL NOT NULL,
	INTERNACAO BIGINT,
	NUMERO_ATENDIMENTO VARCHAR(25),
	NUMERO_AUTORIZACAO VARCHAR(25),
	DATA_AUTORIZACAO TIMESTAMP WITHOUT TIME ZONE,
	DATA_INICIAL_ATENDIMENTO TIMESTAMP WITHOUT TIME ZONE,
	DATA_FINAL_ATENDIMENTO TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE %s.INTERNACAO_ANALISE_CRITICA (
	AUTOID BIGSERIAL NOT NULL,
	INTERNACAO BIGINT,
	DATA_ANALISE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	ANALISE_CRITICA VARCHAR(1200) NOT NULL
);

CREATE TABLE %s.INTERNACAO_SUPORTE_VENTILATORIO (
	AUTOID BIGSERIAL NOT NULL,
	INTERNACAO BIGINT,
	TIPO CHAR(1),
	TIPO_INVASIVO CHAR(1),
	LOCAL CHAR(1),
	DATA_INICIAL TIMESTAMP WITHOUT TIME ZONE,
	DATA_FINAL TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE %s.INTERNACAO_SUPORTE_VENTILATORIO_CONDICAO_ADQUIRIDA (
	AUTOID BIGSERIAL NOT NULL,
	SUPORTE_VENTILATORIO BIGINT NOT NULL,
	CID VARCHAR(15),
	DATA_OCORRENCIA TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE %s.TRANSACAO (
	AUTOID BIGSERIAL NOT NULL,
	STATUS SMALLINT NOT NULL,
	DATA DATE NOT NULL,
	REQUEST BIGINT NOT NULL,
	RESPONSE BIGINT,
	MENSAGEM VARCHAR NOT NULL,
	INDEX BIGINT,
	CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	REVEIVED_AT TIMESTAMP WITHOUT TIME ZONE,
	FINALIZED_AT TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE %s.TRANSACAO_CONTENT (
	AUTOID BIGSERIAL NOT NULL,
	CONTENT VARCHAR NOT NULL
);

CREATE TABLE %s.TRANSACAO_STATUS (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(30) NOT NULL
);

CREATE TABLE %s.ARQUIVO (
	AUTOID BIGSERIAL NOT NULL,
	NOME VARCHAR NOT NULL,
	CONTENT BIGINT NOT NULL,
	CONTENT_TYPE VARCHAR(256) NOT NULL,
	SIZE BIGINT NOT NULL,
	MD5 VARCHAR(32) NOT NULL,
	CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE %s.ARQUIVO_CONTENT (
	AUTOID BIGSERIAL NOT NULL,
	CONTENT BYTEA NOT NULL
);

CREATE TABLE %s.IMPORTACAO (
	AUTOID BIGSERIAL NOT NULL,
	STATUS SMALLINT NOT NULL,
	ARQUIVO BIGINT NOT NULL,
	MENSAGEM VARCHAR NOT NULL,
	INDEX BIGINT,
	CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE %s.IMPORTACAO_STATUS (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(30) NOT NULL
);

CREATE TABLE %s.DIMENSAO (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(35) NOT NULL
);

CREATE TABLE %s.TIPO_INDICADOR (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(40) NOT NULL,
	DIMENSAO SMALLINT NOT NULL,
	DESCRICAO VARCHAR(300) NOT NULL,
	SIGNIFICADO VARCHAR(300) NOT NULL,
	NUMERADOR VARCHAR(300) NOT NULL,
	DENOMINADOR VARCHAR(300) NOT NULL,
	ESTANDARDIZADO BOOLEAN NOT NULL,
	FORMULA VARCHAR NOT NULL
 );

CREATE TABLE %s.INDICADOR (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT,
	HOSPITAL BIGINT,
	QUALIDADE NUMERIC(5,2) NOT NULL,
	EFICIENCIA NUMERIC(5,2) NOT NULL,
	EXPERIENCIA NUMERIC(5,2) NOT NULL,
	CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_USER BIGINT NOT NULL,
	UPDATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_USER BIGINT NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE %s.INDICADOR_VALOR (
	AUTOID BIGSERIAL NOT NULL,
	INDICADOR BIGINT NOT NULL,
	TIPO SMALLINT NOT NULL,
	VALOR NUMERIC(5,2) NOT NULL,
	POPULACAO SMALLINT
);


CREATE TABLE %s.POPULACAO (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(50) NOT NULL,
	CONSIDERAR_IVA BOOLEAN DEFAULT TRUE
);

CREATE TABLE %s.FAIXA_ETARIA (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(100)
);

CREATE TABLE %s.REFERENCIA (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	DATA_REFERENCIA_INICIAL DATE NOT NULL,
	DATA_REFERENCIA_FINAL DATE NOT NULL,
	INICIO_VIGENCIA DATE NOT NULL,
	FIM_VIGENCIA DATE
);

CREATE TABLE %s.TIPO_PERGUNTA (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.TIPO_ALTERNATIVA (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.QUESTIONARIO (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(300),
	VERSION BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE %s.PERGUNTA (
	AUTOID BIGSERIAL NOT NULL,
	QUESTIONARIO BIGINT NOT NULL,
	TIPO SMALLINT NOT NULL,
	ATIVO BOOLEAN NOT NULL DEFAULT TRUE,	
	DESCRICAO VARCHAR NOT NULL,	
	PONTUA BOOLEAN NOT NULL DEFAULT FALSE,
	OBRIGATORIO BOOLEAN NOT NULL DEFAULT TRUE,
	SEQUENCIA SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE %s.ALTERNATIVA (
	AUTOID BIGSERIAL NOT NULL,
	PERGUNTA BIGINT NOT NULL,
	TIPO BIGINT NOT NULL,
	ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
	DESCRICAO VARCHAR,
	PESO SMALLINT,
	SEQUENCIA SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE %s.QUESTIONARIO_RESPOSTA (
	AUTOID BIGSERIAL NOT NULL,
	INTERNACAO BIGINT NOT NULL,
	QUESTIONARIO BIGINT NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 1,
	CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_USER BIGINT NOT NULL
);

CREATE TABLE %s.QUESTIONARIO_RESPOSTA_ALTERNATIVA (
	AUTOID BIGSERIAL NOT NULL,
	QUESTIONARIO BIGINT NOT NULL,
	PERGUNTA BIGINT NOT NULL,
	ALTERNATIVA BIGINT,
	RESPOSTA VARCHAR
);

CREATE TABLE %s.EQUIPE_MEDICA(
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	NOME VARCHAR(150) NOT NULL
);

CREATE TABLE %s.EQUIPE_MEDICA_MEDICO (
	AUTOID BIGSERIAL NOT NULL,
	EQUIPE BIGINT NOT NULL,
	MEDICO BIGINT NOT NULL,
	ESPECIALIDADE BIGINT NOT NULL,
	CHEFE_EQUIPE BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE %s.INDICADOR_META_HEADER (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	HOSPITAL BIGINT,
	VERSION BIGINT,
	UPDATED_USER BIGINT,
	UPDATED_AT TIMESTAMP,
	CREATED_USER BIGINT,
	CREATED_AT TIMESTAMP
);

CREATE TABLE %s.INDICADOR_META_IVA (
	AUTOID BIGSERIAL NOT NULL,
	INDICADOR_META_HEADER BIGINT NOT NULL,
	POPULACAO SMALLINT NOT NULL,
	TIPO_INDICADOR SMALLINT NOT NULL,
	META NUMERIC(5,2) NOT NULL
);

CREATE TABLE %s.INDICADOR_META_IMA (
	AUTOID BIGSERIAL NOT NULL,
	INDICADOR_META_HEADER BIGINT NOT NULL,
	POPULACAO SMALLINT NOT NULL,
	TIPO_INDICADOR BIGINT NOT NULL,
	META NUMERIC(5,2) NOT NULL
);

CREATE TABLE %s.TIPO_INDICADOR_IMA ( 
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(150) NOT NULL
);

CREATE TABLE %s.INDICADOR_IMA_HEADER (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL, 
	HOSPITAL BIGINT,
	PROCESSO_TRABALHO NUMERIC(5,2) NOT NULL,
	APRENDIZADO_CONHECIMENTO NUMERIC(5,2) NOT NULL,
	VERSION BIGINT,
	UPDATED_USER BIGINT,
	UPDATED_AT TIMESTAMP,
	CREATED_USER BIGINT,
	CREATED_AT TIMESTAMP
);

CREATE TABLE %s.DIMENSAO_IMA (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(150) NOT NULL
);

CREATE TABLE %s.INDICADOR_IMA (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	TIPO_INDICADOR SMALLINT NOT NULL,
	NOME VARCHAR(150) NOT NULL,
	SIGNIFICADO VARCHAR(300),
	FORMULA VARCHAR(300),
	ESTANDARDIZADO BOOLEAN DEFAULT FALSE,
	NUMERO_MAXIMO_OCORRENCIA INT,
	DIMENSAO SMALLINT NOT NULL,
	PERIODICIDADE SMALLINT,
	DIRECAO SMALLINT,
	PESO_OCORRENCIA NUMERIC(5,2)
);

CREATE TABLE %s.INDICADOR_IMA_VALOR (
	AUTOID BIGSERIAL NOT NULL,
	INDICADOR_HEADER BIGINT NOT NULL,
	INDICADOR_IMA BIGINT NOT NULL,
	POPULACAO SMALLINT NOT NULL,
	PESO NUMERIC(5,2) NOT NULL
);

CREATE TABLE %s.TIPO_PERIODICIDADE (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.TIPO_DIRECAO_RESULTADO (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.COMPETENCIA (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_FIM DATE NOT NULL
);

CREATE TABLE %s.INDICADOR_IPA_HEADER (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT NOT NULL,
	HOSPITAL BIGINT,
	IVA numeric(5,2) NOT NULL,
	IMA numeric(5,2) NOT NULL,
	UPDATED_AT timestamp without time zone,
    CREATED_USER bigint,
    CREATED_AT timestamp without time zone,
    UPDATED_USER bigint,
    VERSION bigint
);

CREATE TABLE %s.INTEGRACAO_IMA (
	AUTOID BIGSERIAL NOT NULL,
	INSTITUICAO BIGINT NOT NULL,
	HOSPITAL BIGINT NOT NULL,
	MEDICO BIGINT NOT NULL,
	ESPECIALIDADE BIGINT,
	POPULACAO SMALLINT,
	FAIXA_ETARIA SMALLINT,
	COMPETENCIA VARCHAR(8) NOT NULL,
	INDICADOR BIGINT NOT NULL,
	NUMERADOR NUMERIC(5,2),
	DENOMINADOR NUMERIC(5,2),
	OCORRENCIA SMALLINT
);

CREATE TABLE %s.TRANSACAO_IMA (
	AUTOID BIGSERIAL NOT NULL,
	NUMERO_TRANSACAO VARCHAR(10) NOT NULL,
	REQUEST BIGINT,
	RESPONSE BIGINT,
	STATUS SMALLINT NOT NULL,
    MENSAGEM character varying COLLATE pg_catalog.default NOT NULL,
    CREATED_AT timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE %s.STATUS_RELATORIO (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);

CREATE TABLE %s.AGENDAMENTO_RELATORIO (
	AUTOID BIGSERIAL NOT NULL,
	AGENDAMENTO_RELATORIO_FILTRO BIGINT NOT NULL,
	USUARIO BIGINT NOT NULL,
	DATA_INICIO_GERACAO timestamp without time zone NOT NULL,
	DATA_FIM_GERACAO timestamp without time zone,
	ARQUIVO BIGINT,
	STATUS SMALLINT,
	CONCLUSAO INT, --para gravar a porcentagem de finalização 
	DOWNLOAD_REALIZADO BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE %s.AGENDAMENTO_RELATORIO_FILTRO (
	AUTOID BIGSERIAL NOT NULL,
	GRUPO BIGINT,
	POPULACAO SMALLINT,
	FAIXA_ETARIA SMALLINT,
	ESPECIALIDADE BIGINT,
	INSTITUICAO BIGINT,
	HOSPITAL BIGINT,
	MEDICO BIGINT,
	DATA_INICIAL DATE,
	DATA_FINAL DATE,
	EQUIPE_MEDICA BIGINT,
	PASSOU_CTI BOOLEAN,
	LONGA_PERMANENCIA BOOLEAN,
	CARATER_INTERNACAO INTEGER,
	TIPO_ARQUIVO SMALLINT NOT NULL
);

CREATE TABLE %s.TIPO_ARQUIVO_RELATORIO (
	CODIGO SMALLINT NOT NULL,
	TERMO VARCHAR(50) NOT NULL
);


/************************************************************************************************************/
-- CREATE PRIMARY KEYS
/************************************************************************************************************/
ALTER TABLE %s.GRUPO ADD CONSTRAINT PK_GRUPO PRIMARY KEY (AUTOID);
ALTER TABLE %s.CONFIGURACAO_APLICACAO ADD CONSTRAINT PK_CONFIGURACAO_APLICACAO PRIMARY KEY (AUTOID);
ALTER TABLE %s.CONFIGURACAO_EMAIL ADD CONSTRAINT PK_CONFIGURACAO_EMAIL PRIMARY KEY (AUTOID);
ALTER TABLE %s.CONFIGURACAO_WEBSERVICE ADD CONSTRAINT PK_CONFIGURACAO_WEBSERVICE PRIMARY KEY (AUTOID);
ALTER TABLE %s.LOG ADD CONSTRAINT PK_LOG PRIMARY KEY (AUTOID);
ALTER TABLE %s.LOG_ACAO ADD CONSTRAINT PK_LOG_ACAO PRIMARY KEY (CODIGO);
ALTER TABLE %s.ESTADO ADD CONSTRAINT PK_ESTADO PRIMARY KEY (CODIGO);
ALTER TABLE %s.PERMISSAO ADD CONSTRAINT PK_PERMISSAO PRIMARY KEY (CODIGO);
ALTER TABLE %s.PERFIL ADD CONSTRAINT PK_PERFIL PRIMARY KEY (AUTOID);
ALTER TABLE %s.PERFIL_PERMISSAO ADD CONSTRAINT PK_PERFIL_PERMISSAO PRIMARY KEY (PERFIL,PERMISSAO);
ALTER TABLE %s.USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (AUTOID);
ALTER TABLE %s.USUARIO_ACESSO ADD CONSTRAINT PK_USUARIO_ACESSO PRIMARY KEY (AUTOID);
ALTER TABLE %s.SITUACAO_INTERNACAO ADD CONSTRAINT PK_SITUACAO_INTERNACAO PRIMARY KEY (CODIGO);
ALTER TABLE %s.CARATER_INTERNACAO ADD CONSTRAINT PK_CARATER_INTERNACAO PRIMARY KEY (CODIGO);
ALTER TABLE %s.CONDICAO_ALTA ADD CONSTRAINT PK_CONDICAO_ALTA PRIMARY KEY (CODIGO);
ALTER TABLE %s.CONDICAO_ALTA_CTI ADD CONSTRAINT PK_CONDICAO_ALTA_CTI PRIMARY KEY (CODIGO);
ALTER TABLE %s.HOSPITAL_INTERNACAO_ANTERIOR ADD CONSTRAINT PK_HOSPITAL_INTERNACAO_ANTERIOR PRIMARY KEY (CODIGO);
ALTER TABLE %s.PROCEDENCIA ADD CONSTRAINT PK_PROCEDENCIA PRIMARY KEY (CODIGO);
ALTER TABLE %s.MODALIDADE_INTERNACAO ADD CONSTRAINT PK_MODALIDADE_INTERNACAO PRIMARY KEY (CODIGO);
ALTER TABLE %s.VENTILACAO_MECANICA_TOTAL_HORAS ADD CONSTRAINT PK_VENTILACAO_MECANICA_TOTAL_HORAS PRIMARY KEY (CODIGO);
ALTER TABLE %s.CID ADD CONSTRAINT PK_CID PRIMARY KEY (CODIGO);
ALTER TABLE %s.SEXO ADD CONSTRAINT PK_SEXO PRIMARY KEY (CODIGO);
ALTER TABLE %s.ATUACAO_MEDICA ADD CONSTRAINT PK_ATUACAO_MEDICA PRIMARY KEY (CODIGO);
ALTER TABLE %s.RISCO_READMISSAO ADD CONSTRAINT PK_RISCO_READMISSAO PRIMARY KEY (CODIGO);
ALTER TABLE %s.CODIGO_DRG ADD CONSTRAINT PK_CODIGO_DRG PRIMARY KEY (CODIGO);
ALTER TABLE %s.TIPO_DRG ADD CONSTRAINT PK_TIPO_DRG PRIMARY KEY (CODIGO);
ALTER TABLE %s.MDC ADD CONSTRAINT PK_MDC PRIMARY KEY (CODIGO);
ALTER TABLE %s.SUPORTE_VENTILATORIO_TIPO ADD CONSTRAINT PK_SUPORTE_VENTILATORIO_TIPO PRIMARY KEY (CODIGO);
ALTER TABLE %s.SUPORTE_VENTILATORIO_TIPO_INVASIVO ADD CONSTRAINT PK_SUPORTE_VENTILATORIO_TIPO_INVASIVO PRIMARY KEY (CODIGO);
ALTER TABLE %s.SUPORTE_VENTILATORIO_LOCAL ADD CONSTRAINT PK_SUPORTE_VENTILATORIO_LOCAL PRIMARY KEY (CODIGO);
ALTER TABLE %s.PROCEDIMENTO ADD CONSTRAINT PK_PROCEDIMENTO PRIMARY KEY (AUTOID);
ALTER TABLE %s.ESPECIALIDADE ADD CONSTRAINT PK_ESPECIALIDADE PRIMARY KEY (AUTOID);
ALTER TABLE %s.HOSPITAL ADD CONSTRAINT PK_HOSPITAL PRIMARY KEY (AUTOID);
ALTER TABLE %s.INSTITUICAO ADD CONSTRAINT PK_INSTITUICAO PRIMARY KEY (AUTOID);
ALTER TABLE %s.BENEFICIARIO ADD CONSTRAINT PK_BENEFICIARIO PRIMARY KEY (AUTOID);
ALTER TABLE %s.MEDICO ADD CONSTRAINT PK_MEDICO PRIMARY KEY (AUTOID);
ALTER TABLE %s.MEDICO_ESPECIALIDADE ADD CONSTRAINT PK_MEDICO_ESPECIALIDADE PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT PK_INTERNACAO PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_MEDICO ADD CONSTRAINT PK_INTERNACAO_MEDICO PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_CID_PRINCIPAL ADD CONSTRAINT PK_INTERNACAO_CID_PRINCIPAL PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_CID_SECUNDARIO ADD CONSTRAINT PK_INTERNACAO_CID_SECUNDARIO PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_DRG_REFINADO ADD CONSTRAINT PK_INTERNACAO_DRG_REFINADO PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_DRG_BRASIL ADD CONSTRAINT PK_INTERNACAO_DRG_BRASIL PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_PROCEDIMENTO ADD CONSTRAINT PK_INTERNACAO_PROCEDIMENTO PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_PROCEDIMENTO_MEDICO ADD CONSTRAINT PK_INTERNACAO_PROCEDIMENTO_MEDICO PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_CTI ADD CONSTRAINT PK_INTERNACAO_CTI PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_RECEM_NASCIDO ADD CONSTRAINT PK_INTERNACAO_RECEM_NASCIDO PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_CONDICAO_ADQUIRIDA ADD CONSTRAINT PK_INTERNACAO_CONDICAO_ADQUIRIDA PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_ALTA_ADMINISTRATIVA ADD CONSTRAINT PK_INTERNACAO_ALTA_ADMINISTRATIVA PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_ANALISE_CRITICA ADD CONSTRAINT PK_INTERNACAO_ANALISE_CRITICA PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_SUPORTE_VENTILATORIO ADD CONSTRAINT PK_INTERNACAO_SUPORTE_VENTILATORIO PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTERNACAO_SUPORTE_VENTILATORIO_CONDICAO_ADQUIRIDA ADD CONSTRAINT PK_INTERNACAO_SUPORTE_VENTILATORIO_CONDICAO_ADQUIRIDA PRIMARY KEY (AUTOID);
ALTER TABLE %s.TRANSACAO ADD CONSTRAINT PK_TRANSACAO PRIMARY KEY (AUTOID);
ALTER TABLE %s.TRANSACAO_CONTENT ADD CONSTRAINT PK_TRANSACAO_CONTENT PRIMARY KEY (AUTOID);
ALTER TABLE %s.TRANSACAO_STATUS ADD CONSTRAINT PK_TRANSACAO_STATUS PRIMARY KEY (CODIGO);
ALTER TABLE %s.ARQUIVO ADD CONSTRAINT PK_ARQUIVO PRIMARY KEY (AUTOID);
ALTER TABLE %s.ARQUIVO_CONTENT ADD CONSTRAINT PK_ARQUIVO_CONTENT PRIMARY KEY (AUTOID);
ALTER TABLE %s.IMPORTACAO ADD CONSTRAINT PK_IMPORTACAO PRIMARY KEY (AUTOID);
ALTER TABLE %s.IMPORTACAO_STATUS ADD CONSTRAINT PK_IMPORTACAO_STATUS PRIMARY KEY (CODIGO);
ALTER TABLE %s.DIMENSAO ADD CONSTRAINT PK_DIMENSAO PRIMARY KEY (CODIGO);
ALTER TABLE %s.TIPO_INDICADOR ADD CONSTRAINT PK_TIPO_INDICADOR PRIMARY KEY (CODIGO);
ALTER TABLE %s.INDICADOR ADD CONSTRAINT PK_INDICADOR PRIMARY KEY (AUTOID);
ALTER TABLE %s.INDICADOR_VALOR ADD CONSTRAINT PK_INDICADOR_VALOR PRIMARY KEY (AUTOID);
--ALTER TABLE %s.INDICADOR_VALOR_POPULACAO ADD CONSTRAINT PK_INDICADOR_VALOR_POPULACAO PRIMARY KEY (AUTOID);
ALTER TABLE %s.POPULACAO ADD CONSTRAINT PK_POPULACAO PRIMARY KEY (CODIGO);
ALTER TABLE %s.FAIXA_ETARIA ADD CONSTRAINT PK_FAIXA_ETARIA PRIMARY KEY (CODIGO);
ALTER TABLE %s.REFERENCIA ADD CONSTRAINT PK_REFERENCIA PRIMARY KEY (AUTOID);
ALTER TABLE %s.TIPO_PERGUNTA ADD CONSTRAINT PK_TIPO_PERGUNTA	PRIMARY KEY (CODIGO);
ALTER TABLE %s.TIPO_ALTERNATIVA ADD CONSTRAINT PK_TIPO_ALTERNATIVA	PRIMARY KEY (CODIGO);
ALTER TABLE %s.QUESTIONARIO ADD CONSTRAINT PK_QUESTIONARIO PRIMARY KEY (AUTOID);
ALTER TABLE %s.PERGUNTA ADD CONSTRAINT PK_PERGUNTA PRIMARY KEY (AUTOID);
ALTER TABLE %s.ALTERNATIVA ADD CONSTRAINT PK_ALTERNATIVA	PRIMARY KEY (AUTOID);
ALTER TABLE %s.QUESTIONARIO_RESPOSTA ADD CONSTRAINT PK_QUESTIONARIO_RESPOSTA PRIMARY KEY (AUTOID);
ALTER TABLE %s.QUESTIONARIO_RESPOSTA_ALTERNATIVA ADD CONSTRAINT PK_QUESTIONARIO_RESPOSTA_ALTERNATIVA PRIMARY KEY (AUTOID);
ALTER TABLE %s.EQUIPE_MEDICA ADD CONSTRAINT PK_EQUIPE_MEDICA PRIMARY KEY (AUTOID);
ALTER TABLE %s.EQUIPE_MEDICA_MEDICO ADD CONSTRAINT PK_EQUIPE_MEDICA_MEDICO PRIMARY KEY (AUTOID);
ALTER TABLE %s.INDICADOR_META_HEADER ADD CONSTRAINT PK_INDICADOR_META_HEADER PRIMARY KEY (AUTOID);
ALTER TABLE %s.INDICADOR_META_IVA ADD CONSTRAINT PK_INDICADOR_META_IVA PRIMARY KEY (AUTOID);
ALTER TABLE %s.INDICADOR_META_IMA ADD CONSTRAINT PK_INDICADOR_META_IMA PRIMARY KEY (AUTOID);
ALTER TABLE %s.TIPO_INDICADOR_IMA ADD CONSTRAINT PK_TIPO_INDICADOR_IMA PRIMARY KEY (CODIGO);
ALTER TABLE %s.INDICADOR_IMA_HEADER ADD CONSTRAINT PK_INDICADOR_IMA_HEADER PRIMARY KEY (AUTOID);
ALTER TABLE %s.DIMENSAO_IMA ADD CONSTRAINT PK_DIMENSAO_IMA PRIMARY KEY (CODIGO);
ALTER TABLE %s.INDICADOR_IMA ADD CONSTRAINT PK_INDICADOR_IMA PRIMARY KEY (AUTOID);
ALTER TABLE %s.INDICADOR_IMA_VALOR ADD CONSTRAINT PK_INDICADOR_IMA_VALOR PRIMARY KEY (AUTOID);
ALTER TABLE %s.TIPO_PERIODICIDADE ADD CONSTRAINT PK_TIPO_PERIODICIDADE PRIMARY KEY (CODIGO);
ALTER TABLE %s.TIPO_DIRECAO_RESULTADO ADD CONSTRAINT PK_TIPO_DIRECAO_RESULTADO PRIMARY KEY (CODIGO);
ALTER TABLE %s.COMPETENCIA ADD CONSTRAINT PK_COMPETENCIA PRIMARY KEY (AUTOID);
ALTER TABLE %s.INDICADOR_IPA_HEADER ADD CONSTRAINT PK_INDICADOR_IPA_HEADER PRIMARY KEY (AUTOID);
ALTER TABLE %s.INTEGRACAO_IMA ADD CONSTRAINT PK_INTEGRACAO_IMA PRIMARY KEY (AUTOID);
ALTER TABLE %s.TRANSACAO_IMA ADD CONSTRAINT PK_TRANSACAO_IMA PRIMARY KEY (AUTOID);
ALTER TABLE %s.STATUS_RELATORIO ADD CONSTRAINT PK_STATUS_RELATORIO PRIMARY KEY (CODIGO);
ALTER TABLE %s.AGENDAMENTO_RELATORIO ADD CONSTRAINT PK_AGENDAMENTO_RELATORIO PRIMARY KEY (AUTOID);
ALTER TABLE %s.AGENDAMENTO_RELATORIO_FILTRO ADD CONSTRAINT PK_AGENDAMENTO_RELATORIO_FILTRO PRIMARY KEY (AUTOID);
ALTER TABLE %s.TIPO_ARQUIVO_RELATORIO ADD CONSTRAINT PK_TIPO_ARQUIVO_RELATORIO PRIMARY KEY (CODIGO);

/************************************************************************************************************/
-- CREATE FOREIGN KEYS
/************************************************************************************************************/
ALTER TABLE %s.LOG ADD CONSTRAINT FK_LOG_ACAO FOREIGN KEY (ACAO) REFERENCES %s.LOG_ACAO (CODIGO);
ALTER TABLE %s.LOG ADD CONSTRAINT FK_LOG_CREATED_USER FOREIGN KEY (CREATED_USER) REFERENCES %s.USUARIO (AUTOID);

ALTER TABLE %s.PERMISSAO ADD CONSTRAINT FK_PERMISSAO_PERMISSAO_PAI FOREIGN KEY (PERMISSAO_PAI) REFERENCES %s.PERMISSAO (CODIGO);

ALTER TABLE %s.PERFIL ADD CONSTRAINT FK_PERFIL_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);

ALTER TABLE %s.PERFIL_PERMISSAO ADD CONSTRAINT FK_PERFIL_PERMISSAO_PERFIL FOREIGN KEY (PERFIL) REFERENCES %s.PERFIL (AUTOID);
ALTER TABLE %s.PERFIL_PERMISSAO ADD CONSTRAINT FK_PERFIL_PERMISSAO_PERMISSAO FOREIGN KEY (PERMISSAO) REFERENCES %s.PERMISSAO (CODIGO);

ALTER TABLE %s.USUARIO ADD CONSTRAINT FK_USUARIO_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);
ALTER TABLE %s.USUARIO ADD CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY (PERFIL) REFERENCES %s.PERFIL (AUTOID);
ALTER TABLE %s.USUARIO ADD CONSTRAINT FK_USUARIO_INSTITUICAO FOREIGN KEY (INSTITUICAO) REFERENCES %s.INSTITUICAO (AUTOID);
ALTER TABLE %s.USUARIO ADD CONSTRAINT FK_USUARIO_HOSPITAL FOREIGN KEY (HOSPITAL) REFERENCES %s.HOSPITAL (AUTOID);
ALTER TABLE %s.USUARIO ADD CONSTRAINT FK_USUARIO_MEDICO FOREIGN KEY (MEDICO) REFERENCES %s.MEDICO (AUTOID);


ALTER TABLE %s.USUARIO_ACESSO ADD CONSTRAINT FK_USUARIO_ACESSO_USUARIO FOREIGN KEY (USUARIO) REFERENCES %s.USUARIO (AUTOID);

ALTER TABLE %s.HOSPITAL ADD CONSTRAINT FK_HOSPITAL_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);

ALTER TABLE %s.INSTITUICAO ADD CONSTRAINT FK_INSTITUICAO_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);

ALTER TABLE %s.BENEFICIARIO ADD CONSTRAINT FK_BENEFICIARIO_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);
ALTER TABLE %s.BENEFICIARIO ADD CONSTRAINT FK_BENEFICIARIO_SEXO FOREIGN KEY (SEXO) REFERENCES %s.SEXO (CODIGO);

ALTER TABLE %s.MEDICO ADD CONSTRAINT FK_MEDICO_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);
ALTER TABLE %s.MEDICO ADD CONSTRAINT FK_MEDICO_UF FOREIGN KEY (UF) REFERENCES %s.ESTADO (CODIGO);

ALTER TABLE %s.MEDICO_ESPECIALIDADE ADD CONSTRAINT FK_MEDICO_ESPECIALIDADE_MEDICO FOREIGN KEY (MEDICO) REFERENCES %s.MEDICO (AUTOID);
ALTER TABLE %s.MEDICO_ESPECIALIDADE ADD CONSTRAINT FK_MEDICO_ESPECIALIDADE_ESPECIALIDADE FOREIGN KEY (ESPECIALIDADE) REFERENCES %s.ESPECIALIDADE (AUTOID);

ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_INSTITUICAO FOREIGN KEY (INSTITUICAO) REFERENCES %s.INSTITUICAO (AUTOID);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_SITUACAO FOREIGN KEY (SITUACAO) REFERENCES %s.SITUACAO_INTERNACAO (CODIGO);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_CARATER_INTERNACAO FOREIGN KEY (CARATER_INTERNACAO) REFERENCES %s.CARATER_INTERNACAO (CODIGO);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_CONDICAO_ALTA FOREIGN KEY (CONDICAO_ALTA) REFERENCES %s.CONDICAO_ALTA (CODIGO);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_HOSPITAL_INTERNACAO_ANTERIOR FOREIGN KEY (HOSPITAL_INTERNACAO_ANTERIOR) REFERENCES %s.HOSPITAL_INTERNACAO_ANTERIOR (CODIGO);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_PROCEDENCIA FOREIGN KEY (PROCEDENCIA) REFERENCES %s.PROCEDENCIA (CODIGO);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_MODALIDADE_INTERNACAO FOREIGN KEY (MODALIDADE_INTERNACAO) REFERENCES %s.MODALIDADE_INTERNACAO (CODIGO);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_TOTAL_HORAS_VENTILACAO_MECANICA FOREIGN KEY (TOTAL_HORAS_VENTILACAO_MECANICA) REFERENCES %s.VENTILACAO_MECANICA_TOTAL_HORAS (CODIGO);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_RISCO_READMISSAO FOREIGN KEY (RISCO_READMISSAO) REFERENCES %s.RISCO_READMISSAO (CODIGO);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_CID_PRINCIPAL FOREIGN KEY (CID_PRINCIPAL) REFERENCES %s.INTERNACAO_CID_PRINCIPAL (AUTOID);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_HOSPITAL FOREIGN KEY (HOSPITAL) REFERENCES %s.HOSPITAL (AUTOID);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_BENEFICIARIO FOREIGN KEY (BENEFICIARIO) REFERENCES %s.BENEFICIARIO (AUTOID);
ALTER TABLE %s.INTERNACAO ADD CONSTRAINT FK_INTERNACAO_DRG_BRASIL FOREIGN KEY (DRG_BRASIL) REFERENCES %s.INTERNACAO_DRG_BRASIL (AUTOID);

ALTER TABLE %s.INTERNACAO_MEDICO ADD CONSTRAINT FK_INTERNACAO_MEDICO_INTERNACAO FOREIGN KEY (INTERNACAO) REFERENCES %s.INTERNACAO (AUTOID);
ALTER TABLE %s.INTERNACAO_MEDICO ADD CONSTRAINT FK_INTERNACAO_MEDICO_MEDICO FOREIGN KEY (MEDICO) REFERENCES %s.MEDICO (AUTOID);
ALTER TABLE %s.INTERNACAO_MEDICO ADD CONSTRAINT FK_INTERNACAO_MEDICO_ESPECIALIDADE FOREIGN KEY (ESPECIALIDADE) REFERENCES %s.MEDICO_ESPECIALIDADE (AUTOID);
ALTER TABLE %s.INTERNACAO_MEDICO ADD CONSTRAINT FK_INTERNACAO_MEDICO_ATUACAO FOREIGN KEY (ATUACAO) REFERENCES %s.ATUACAO_MEDICA (CODIGO);

ALTER TABLE %s.INTERNACAO_CID_PRINCIPAL ADD CONSTRAINT FK_CID_PRIMARIO_CID FOREIGN KEY (CID) REFERENCES %s.CID (CODIGO);

ALTER TABLE %s.INTERNACAO_CID_SECUNDARIO ADD CONSTRAINT FK_INTERNACAO_CID_SECUNDARIO_INTERNACAO FOREIGN KEY (INTERNACAO) REFERENCES %s.INTERNACAO (AUTOID);
ALTER TABLE %s.INTERNACAO_CID_SECUNDARIO ADD CONSTRAINT FK_INTERNACAO_CID_SECUNDARIO_CID FOREIGN KEY (CID) REFERENCES %s.CID (CODIGO);

ALTER TABLE %s.INTERNACAO_DRG_BRASIL ADD CONSTRAINT FK_INTERNACAO_DRG_BRASIL_CODIGO_DRG FOREIGN KEY (CODIGO_DRG) REFERENCES %s.CODIGO_DRG (CODIGO);
ALTER TABLE %s.INTERNACAO_DRG_BRASIL ADD CONSTRAINT FK_INTERNACAO_DRG_BRASIL_TIPO_DRG FOREIGN KEY (TIPO_DRG) REFERENCES %s.TIPO_DRG (CODIGO);
ALTER TABLE %s.INTERNACAO_DRG_BRASIL ADD CONSTRAINT FK_INTERNACAO_DRG_BRASIL_MDC FOREIGN KEY (MDC) REFERENCES %s.MDC (CODIGO);
ALTER TABLE %s.INTERNACAO_DRG_BRASIL ADD CONSTRAINT FK_INTERNACAO_DRG_BRASIL_DRG_REFINADO FOREIGN KEY (DRG_REFINADO) REFERENCES %s.INTERNACAO_DRG_REFINADO (AUTOID);

ALTER TABLE %s.INTERNACAO_PROCEDIMENTO ADD CONSTRAINT FK_INTERNACAO_PROCEDIMENTO_INTERNACAO FOREIGN KEY (INTERNACAO) REFERENCES %s.INTERNACAO (AUTOID);
ALTER TABLE %s.INTERNACAO_PROCEDIMENTO ADD CONSTRAINT FK_INTERNACAO_PROCEDIMENTO_PROCEDIMENTO FOREIGN KEY (PROCEDIMENTO) REFERENCES %s.PROCEDIMENTO (AUTOID);

ALTER TABLE %s.INTERNACAO_PROCEDIMENTO_MEDICO ADD CONSTRAINT FK_INTERNACAO_PROCEDIMENTO_MEDICO_PROCEDIMENTO FOREIGN KEY (PROCEDIMENTO) REFERENCES %s.INTERNACAO_PROCEDIMENTO (AUTOID);
ALTER TABLE %s.INTERNACAO_PROCEDIMENTO_MEDICO ADD CONSTRAINT FK_INTERNACAO_PROCEDIMENTO_MEDICO_MEDICO FOREIGN KEY (MEDICO) REFERENCES %s.MEDICO (AUTOID);
ALTER TABLE %s.INTERNACAO_PROCEDIMENTO_MEDICO ADD CONSTRAINT FK_INTERNACAO_PROCEDIMENTO_MEDICO_ESPECIALIDADE FOREIGN KEY (ESPECIALIDADE) REFERENCES %s.MEDICO_ESPECIALIDADE (AUTOID);

ALTER TABLE %s.INTERNACAO_CTI ADD CONSTRAINT FK_INTERNACAO_CTI_INTERNACAO FOREIGN KEY (INTERNACAO) REFERENCES %s.INTERNACAO (AUTOID);
ALTER TABLE %s.INTERNACAO_CTI ADD CONSTRAINT FK_INTERNACAO_CTI_CONDICAO_ALTA FOREIGN KEY (CONDICAO_ALTA) REFERENCES %s.CONDICAO_ALTA_CTI (CODIGO);
ALTER TABLE %s.INTERNACAO_CTI ADD CONSTRAINT FK_INTERNACAO_CTI_MEDICO FOREIGN KEY (MEDICO) REFERENCES %s.MEDICO (AUTOID);
ALTER TABLE %s.INTERNACAO_CTI ADD CONSTRAINT FK_INTERNACAO_CTI_ESPECIALIDADE FOREIGN KEY (ESPECIALIDADE) REFERENCES %s.MEDICO_ESPECIALIDADE (AUTOID);
ALTER TABLE %s.INTERNACAO_CTI ADD CONSTRAINT FK_INTERNACAO_CTI_HOSPITAL FOREIGN KEY (HOSPITAL) REFERENCES %s.HOSPITAL (AUTOID);
ALTER TABLE %s.INTERNACAO_CTI ADD CONSTRAINT FK_INTERNACAO_CTI_CID_PRINCIPAL FOREIGN KEY (CID_PRINCIPAL) REFERENCES %s.INTERNACAO_CID_PRINCIPAL (AUTOID);
ALTER TABLE %s.INTERNACAO_CTI ADD CONSTRAINT FK_INTERNACAO_CTI_DRG_BRASIL FOREIGN KEY (DRG_BRASIL) REFERENCES %s.INTERNACAO_DRG_BRASIL (AUTOID);

ALTER TABLE %s.INTERNACAO_RECEM_NASCIDO ADD CONSTRAINT FK_INTERNACAO_RECEM_NASCIDO_INTERNACAO FOREIGN KEY (INTERNACAO) REFERENCES %s.INTERNACAO (AUTOID);
ALTER TABLE %s.INTERNACAO_RECEM_NASCIDO ADD CONSTRAINT FK_INTERNACAO_RECEM_NASCIDO_SEXO FOREIGN KEY (SEXO) REFERENCES %s.SEXO (CODIGO);

ALTER TABLE %s.INTERNACAO_CONDICAO_ADQUIRIDA ADD CONSTRAINT FK_INTERNACAO_CONDICAO_ADQUIRIDA_INTERNACAO FOREIGN KEY (INTERNACAO) REFERENCES %s.INTERNACAO (AUTOID);
ALTER TABLE %s.INTERNACAO_CONDICAO_ADQUIRIDA ADD CONSTRAINT FK_INTERNACAO_CONDICAO_ADQUIRIDA_CID FOREIGN KEY (CID) REFERENCES %s.CID (CODIGO);
ALTER TABLE %s.INTERNACAO_CONDICAO_ADQUIRIDA ADD CONSTRAINT FK_INTERNACAO_CONDICAO_ADQUIRIDA_MEDICO FOREIGN KEY (MEDICO) REFERENCES %s.MEDICO (AUTOID);
ALTER TABLE %s.INTERNACAO_CONDICAO_ADQUIRIDA ADD CONSTRAINT FK_INTERNACAO_CONDICAO_ADQUIRIDA_ESPECIALIDADE FOREIGN KEY (ESPECIALIDADE) REFERENCES %s.MEDICO_ESPECIALIDADE (AUTOID);

ALTER TABLE %s.INTERNACAO_ALTA_ADMINISTRATIVA ADD CONSTRAINT FK_INTERNACAO_ALTA_ADMINISTRATIVA_INTERNACAO FOREIGN KEY (INTERNACAO) REFERENCES %s.INTERNACAO (AUTOID);

ALTER TABLE %s.INTERNACAO_ANALISE_CRITICA ADD CONSTRAINT FK_INTERNACAO_ANALISE_CRITICA_INTERNACAO FOREIGN KEY (INTERNACAO) REFERENCES %s.INTERNACAO (AUTOID);

ALTER TABLE %s.INTERNACAO_SUPORTE_VENTILATORIO ADD CONSTRAINT FK_INTERNACAO_SUPORTE_VENTILATORIO_INTERNACAO FOREIGN KEY (INTERNACAO) REFERENCES %s.INTERNACAO (AUTOID);
ALTER TABLE %s.INTERNACAO_SUPORTE_VENTILATORIO ADD CONSTRAINT FK_INTERNACAO_SUPORTE_VENTILATORIO_TIPO FOREIGN KEY (TIPO) REFERENCES %s.SUPORTE_VENTILATORIO_TIPO (CODIGO);
ALTER TABLE %s.INTERNACAO_SUPORTE_VENTILATORIO ADD CONSTRAINT FK_INTERNACAO_SUPORTE_VENTILATORIO_TIPO_INVASIVO FOREIGN KEY (TIPO_INVASIVO) REFERENCES %s.SUPORTE_VENTILATORIO_TIPO_INVASIVO (CODIGO);
ALTER TABLE %s.INTERNACAO_SUPORTE_VENTILATORIO ADD CONSTRAINT FK_INTERNACAO_SUPORTE_VENTILATORIO_LOCAL FOREIGN KEY (LOCAL) REFERENCES %s.SUPORTE_VENTILATORIO_LOCAL (CODIGO);

ALTER TABLE %s.INTERNACAO_SUPORTE_VENTILATORIO_CONDICAO_ADQUIRIDA ADD CONSTRAINT FK_INTERNACAO_SUPORTE_VENTILATORIO_CONDICAO_ADQUIRIDA_SUPORTE FOREIGN KEY (SUPORTE_VENTILATORIO) REFERENCES %s.INTERNACAO_SUPORTE_VENTILATORIO (AUTOID);
ALTER TABLE %s.INTERNACAO_SUPORTE_VENTILATORIO_CONDICAO_ADQUIRIDA ADD CONSTRAINT FK_INTERNACAO_SUPORTE_VENTILATORIO_CONDICAO_ADQUIRIDA_CID FOREIGN KEY (CID) REFERENCES %s.CID (CODIGO);

ALTER TABLE %s.TRANSACAO ADD CONSTRAINT FK_TRANSACAO_STATUS FOREIGN KEY (STATUS) REFERENCES %s.TRANSACAO_STATUS (CODIGO);
ALTER TABLE %s.TRANSACAO ADD CONSTRAINT FK_TRANSACAO_REQUEST FOREIGN KEY (REQUEST) REFERENCES %s.TRANSACAO_CONTENT (AUTOID);
ALTER TABLE %s.TRANSACAO ADD CONSTRAINT FK_TRANSACAO_RESPONSE FOREIGN KEY (RESPONSE) REFERENCES %s.TRANSACAO_CONTENT (AUTOID);

ALTER TABLE %s.ARQUIVO ADD CONSTRAINT FK_ARQUIVO_CONTENT FOREIGN KEY (CONTENT) REFERENCES %s.ARQUIVO_CONTENT (AUTOID);

ALTER TABLE %s.IMPORTACAO ADD CONSTRAINT FK_IMPORTACAO_STATUS FOREIGN KEY (STATUS) REFERENCES %s.IMPORTACAO_STATUS (CODIGO);
ALTER TABLE %s.IMPORTACAO ADD CONSTRAINT FK_IMPORTACAO_ARQUIVO FOREIGN KEY (ARQUIVO) REFERENCES %s.ARQUIVO (AUTOID);

ALTER TABLE %s.TIPO_INDICADOR ADD CONSTRAINT FK_TIPO_INDICADOR_DIMENSAO FOREIGN KEY (DIMENSAO) REFERENCES %s.DIMENSAO (CODIGO);
ALTER TABLE %s.INDICADOR ADD CONSTRAINT FK_INDICADOR_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);
ALTER TABLE %s.INDICADOR ADD CONSTRAINT FK_INDICADOR_HOSPITAL FOREIGN KEY (HOSPITAL) REFERENCES %s.HOSPITAL (AUTOID);
ALTER TABLE %s.INDICADOR ADD CONSTRAINT FK_INDICADOR_CREATED_USER FOREIGN KEY (CREATED_USER) REFERENCES %s.USUARIO (AUTOID);
ALTER TABLE %s.INDICADOR ADD CONSTRAINT FK_INDICADOR_UPDATED_USER FOREIGN KEY (UPDATED_USER) REFERENCES %s.USUARIO (AUTOID);

ALTER TABLE %s.INDICADOR_VALOR ADD CONSTRAINT FK_INDICADOR_VALOR_INDICADOR FOREIGN KEY (INDICADOR) REFERENCES %s.INDICADOR (AUTOID);
ALTER TABLE %s.INDICADOR_VALOR ADD CONSTRAINT FK_INDICADOR_VALOR_TIPO FOREIGN KEY (TIPO) REFERENCES %s.TIPO_INDICADOR (CODIGO);
/*ALTER TABLE %s.INDICADOR_VALOR_POPULACAO ADD CONSTRAINT FK_INDICADOR_VALOR_POPULACAO_INDICADOR_VALOR FOREIGN KEY (INDICADOR_VALOR) REFERENCES %s.INDICADOR_VALOR (AUTOID);
ALTER TABLE %s.INDICADOR_VALOR_POPULACAO ADD CONSTRAINT FK_INDICADOR_VALOR_POPULACAO_POPULACAO FOREIGN KEY (POPULACAO) REFERENCES %s.POPULACAO (CODIGO);*/
ALTER TABLE %s.INDICADOR_VALOR ADD CONSTRAINT FK_INDICADOR_VALOR_POPULACAO FOREIGN KEY (POPULACAO) REFERENCES %s.POPULACAO (CODIGO);
ALTER TABLE %s.REFERENCIA ADD CONSTRAINT FK_REFERENCIA_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO;

ALTER TABLE %s.QUESTIONARIO ADD CONSTRAINT FK_QUESTIONARIO_GRUPO	FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);
ALTER TABLE %s.PERGUNTA ADD CONSTRAINT FK_PERGUNTA_QUESTIONARIO FOREIGN KEY (QUESTIONARIO) REFERENCES %s.QUESTIONARIO (AUTOID);
ALTER TABLE %s.PERGUNTA ADD CONSTRAINT FK_PERGUNTA_TIPO	FOREIGN KEY (TIPO) REFERENCES %s.TIPO_PERGUNTA (CODIGO);
ALTER TABLE %s.ALTERNATIVA ADD CONSTRAINT FK_ALTERNATIVA_PERGUNTA FOREIGN KEY (PERGUNTA) REFERENCES %s.PERGUNTA (AUTOID);
ALTER TABLE %s.ALTERNATIVA ADD CONSTRAINT FK_ALTERNATIVA_TIPO FOREIGN KEY (TIPO) REFERENCES %s.TIPO_ALTERNATIVA (CODIGO);
ALTER TABLE %s.QUESTIONARIO_RESPOSTA ADD CONSTRAINT FK_QUESTIONARIO_RESPOSTA_INTERNACAO FOREIGN KEY (INTERNACAO) REFERENCES %s.INTERNACAO (AUTOID);
ALTER TABLE %s.QUESTIONARIO_RESPOSTA ADD CONSTRAINT FK_QUESTIONARIO_RESPOSTA_QUESTIONARIO FOREIGN KEY (QUESTIONARIO) REFERENCES %s.QUESTIONARIO (AUTOID);
ALTER TABLE %s.QUESTIONARIO_RESPOSTA ADD CONSTRAINT FK_QUESTIONARIO_RESPOSTA_CREATED_USER FOREIGN KEY (CREATED_USER) REFERENCES %s.USUARIO (AUTOID);
ALTER TABLE %s.QUESTIONARIO_RESPOSTA_ALTERNATIVA ADD CONSTRAINT FK_QUESTIONARIO_RESPOSTA_ALTERNATIVA_QUESTIONARIO FOREIGN KEY (QUESTIONARIO) REFERENCES %s.QUESTIONARIO_RESPOSTA (AUTOID);
ALTER TABLE %s.QUESTIONARIO_RESPOSTA_ALTERNATIVA ADD CONSTRAINT FK_QUESTIONARIO_RESPOSTA_ALTERNATIVA_PERGUNTA FOREIGN KEY (PERGUNTA) REFERENCES %s.PERGUNTA (AUTOID);
ALTER TABLE %s.QUESTIONARIO_RESPOSTA_ALTERNATIVA ADD CONSTRAINT FK_QUESTIONARIO_RESPOSTA_ALTERNATIVA_ALTERNATIVA FOREIGN KEY (ALTERNATIVA) REFERENCES %s.ALTERNATIVA (AUTOID);
ALTER TABLE %s.EQUIPE_MEDICA ADD CONSTRAINT FK_EQUIPE_MEDICA_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);
ALTER TABLE %s.EQUIPE_MEDICA_MEDICO ADD CONSTRAINT FK_EQUIPE_MEDICA_MEDICO_EQUIPE FOREIGN KEY (EQUIPE) REFERENCES %s.EQUIPE_MEDICA (AUTOID);
ALTER TABLE %s.EQUIPE_MEDICA_MEDICO ADD CONSTRAINT FK_EQUIPE_MEDICA_MEDICO_MEDICO FOREIGN KEY (MEDICO) REFERENCES %s.MEDICO (AUTOID);
ALTER TABLE %s.EQUIPE_MEDICA_MEDICO ADD CONSTRAINT FK_EQUIPE_MEDICA_MEDICO_ESPECIALIDADE FOREIGN KEY (ESPECIALIDADE) REFERENCES %s.ESPECIALIDADE (AUTOID);
ALTER TABLE %s.INDICADOR_META_HEADER ADD CONSTRAINT FK_INDICADOR_META_HEADER_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);
ALTER TABLE %s.INDICADOR_META_HEADER ADD CONSTRAINT FK_INDICADOR_META_HEADER_HOSPITAL FOREIGN KEY (HOSPITAL) REFERENCES %s.HOSPITAL (AUTOID);
ALTER TABLE %s.INDICADOR_META_IVA ADD CONSTRAINT FK_INDICADOR_META_IVA_HEADER FOREIGN KEY (INDICADOR_META_HEADER) REFERENCES %s.INDICADOR_META_HEADER (AUTOID);
ALTER TABLE %s.INDICADOR_META_IVA ADD CONSTRAINT FK_INDICADOR_META_IVA_POPULACAO FOREIGN KEY (POPULACAO) REFERENCES %s.POPULACAO (CODIGO);
ALTER TABLE %s.INDICADOR_META_IVA ADD CONSTRAINT FK_INDICADOR_META_IVA_TIPO_INDICADOR FOREIGN KEY (TIPO_INDICADOR) REFERENCES %s.TIPO_INDICADOR (CODIGO);
ALTER TABLE %s.INDICADOR_META_IMA ADD CONSTRAINT FK_INDICADOR_META_IMA_HEADER FOREIGN KEY (INDICADOR_META_HEADER) REFERENCES %s.INDICADOR_META_HEADER (AUTOID);
ALTER TABLE %s.INDICADOR_META_IMA ADD CONSTRAINT FK_INDICADOR_META_IMA_POPULACAO FOREIGN KEY (POPULACAO) REFERENCES %s.POPULACAO (CODIGO);
ALTER TABLE %s.INDICADOR_META_IMA ADD CONSTRAINT FK_INDICADOR_META_IMA_INDICADOR_IMA FOREIGN KEY (TIPO_INDICADOR) REFERENCES %s.INDICADOR_IMA (AUTOID);
ALTER TABLE %s.INDICADOR_IMA ADD CONSTRAINT FK_INDICADOR_META_TIPO_INDICADOR FOREIGN KEY (TIPO_INDICADOR) REFERENCES %s.TIPO_INDICADOR_IMA (CODIGO);
ALTER TABLE %s.INDICADOR_IMA ADD CONSTRAINT FK_INDICADOR_IMA_DIMENSAO FOREIGN KEY (DIMENSAO) REFERENCES %s.DIMENSAO (CODIGO);
ALTER TABLE %s.INDICADOR_IMA ADD CONSTRAINT FK_INDICADOR_IMA_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);
ALTER TABLE %s.INDICADOR_IMA_VALOR ADD CONSTRAINT FK_INDICADOR_IMA_VALOR_HEADER FOREIGN KEY (INDICADOR_HEADER) REFERENCES %s.INDICADOR_IMA_HEADER (AUTOID);
ALTER TABLE %s.INDICADOR_IMA ADD CONSTRAINT FK_INDICADOR_IMA_PERIODICIDADE FOREIGN KEY (PERIODICIDADE) REFERENCES %s.TIPO_PERIODICIDADE (CODIGO);
ALTER TABLE %s.INDICADOR_IMA ADD CONSTRAINT FK_INDICADOR_IMA_DIRECAO FOREIGN KEY (DIRECAO) REFERENCES %s.TIPO_DIRECAO_RESULTADO (CODIGO);
ALTER TABLE %s.COMPETENCIA ADD CONSTRAINT FK_COMPETENCIA_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);
ALTER TABLE %s.INDICADOR_IPA_HEADER ADD CONSTRAINT FK_INDICADOR_IPA_HEADER_GRUPO FOREIGN KEY (GRUPO) REFERENCES %s.GRUPO (AUTOID);
ALTER TABLE %s.INDICADOR_IPA_HEADER ADD CONSTRAINT FK_INDICADOR_IPA_HEADER_HOSPITAL FOREIGN KEY (HOSPITAL) REFERENCES %s.HOSPITAL (AUTOID);
ALTER TABLE %s.INTEGRACAO_IMA ADD CONSTRAINT FK_INTEGRACAO_IMA_INSTITUICAO FOREIGN KEY (INSTITUICAO) REFERENCES %s.INSTITUICAO (AUTOID);
ALTER TABLE %s.INTEGRACAO_IMA ADD CONSTRAINT FK_INTEGRACAO_IMA_HOSPITAL FOREIGN KEY (HOSPITAL) REFERENCES %s.HOSPITAL (AUTOID);
ALTER TABLE %s.INTEGRACAO_IMA ADD CONSTRAINT FK_INTEGRACAO_IMA_MEDICO FOREIGN KEY (MEDICO) REFERENCES %s.MEDICO (AUTOID);
ALTER TABLE %s.INTEGRACAO_IMA ADD CONSTRAINT FK_INTEGRACAO_IMA_ESPECIALIDADE FOREIGN KEY (ESPECIALIDADE) REFERENCES %s.ESPECIALIDADE (AUTOID);
ALTER TABLE %s.INTEGRACAO_IMA ADD CONSTRAINT FK_INTEGRACAO_IMA_POPULACAO FOREIGN KEY (POPULACAO) REFERENCES %s.POPULACAO (CODIGO);
ALTER TABLE %s.INTEGRACAO_IMA ADD CONSTRAINT FK_INTEGRACAO_IMA_FAIXA_ETARIA FOREIGN KEY (FAIXA_ETARIA) REFERENCES %s.FAIXA_ETARIA (CODIGO);
ALTER TABLE %s.TRANSACAO_IMA ADD CONSTRAINT FK_TRANSACAO_IMA_STATUS FOREIGN KEY (STATUS) REFERENCES %s.TRANSACAO_STATUS (CODIGO);
ALTER TABLE %s.TRANSACAO_IMA ADD CONSTRAINT FK_TRANSACAO_IMA_TRANSACAO_CONTENT FOREIGN KEY (REQUEST) REFERENCES %s.TRANSACAO_CONTENT (AUTOID);
ALTER TABLE %s.TRANSACAO_IMA ADD CONSTRAINT FK_TRANSACAO_IMA_TRANSACAO_CONTENT_RESPONSE FOREIGN KEY (RESPONSE) REFERENCES %s.TRANSACAO_CONTENT (AUTOID);
ALTER TABLE %s.AGENDAMENTO_RELATORIO ADD CONSTRAINT FK_AGENDAMENTO_RELATORIO_USUARIO FOREIGN KEY (USUARIO) REFERENCES %s.USUARIO (AUTOID);
ALTER TABLE %s.AGENDAMENTO_RELATORIO ADD CONSTRAINT FK_AGENDAMENTO_RELATORIO_ARQUIVO FOREIGN KEY (ARQUIVO) REFERENCES %s.ARQUIVO (AUTOID);
ALTER TABLE %s.AGENDAMENTO_RELATORIO ADD CONSTRAINT FK_AGENDAMENTO_RELATORIO_FILTRO FOREIGN KEY (AGENDAMENTO_RELATORIO_FILTRO) REFERENCES %s.AGENDAMENTO_RELATORIO_FILTRO (AUTOID);
ALTER TABLE %s.AGENDAMENTO_RELATORIO_FILTRO ADD CONSTRAINT FK_AGENDAMENTO_RELATORIO_FILTRO_TIPO FOREIGN KEY (TIPO_ARQUIVO) REFERENCES %s.TIPO_ARQUIVO_RELATORIO (CODIGO);


/************************************************************************************************************/
-- CREATE UNIQUES
/************************************************************************************************************/
ALTER TABLE %s.GRUPO ADD CONSTRAINT UQ_GRUPO_NOME UNIQUE (NOME);

ALTER TABLE %s.PERFIL ADD CONSTRAINT UQ_PERFIL_NOME UNIQUE (GRUPO,NOME);

ALTER TABLE %s.USUARIO ADD CONSTRAINT UQ_USUARIO_LOGIN UNIQUE (LOGIN);

ALTER TABLE %s.PROCEDIMENTO ADD CONSTRAINT UQ_PROCEDIMENTO_CODIGO UNIQUE (CODIGO);

ALTER TABLE %s.ESPECIALIDADE ADD CONSTRAINT UQ_PESPECIALIDADE_NOME UNIQUE (NOME);

ALTER TABLE %s.MEDICO_ESPECIALIDADE ADD CONSTRAINT UQ_MEDICO_ESPECIALIDADE UNIQUE (MEDICO,ESPECIALIDADE);

ALTER TABLE %s.INSTITUICAO ADD CONSTRAINT UQ_INSTITUICAO_CODIGO UNIQUE (GRUPO,CODIGO);

ALTER TABLE %s.HOSPITAL ADD CONSTRAINT UQ_HOSPITAL_CODIGO UNIQUE (GRUPO,CODIGO);

ALTER TABLE %s.BENEFICIARIO ADD CONSTRAINT UQ_BENEFICIARIO_CODIGO_NOME_RN UNIQUE (GRUPO, CODIGO_PACIENTE, NOME, RECEM_NASCIDO);

ALTER TABLE %s.INDICADOR ADD CONSTRAINT UQ_INDICADOR_HOSPITAL UNIQUE (HOSPITAL);

ALTER TABLE %s.INTERNACAO ADD CONSTRAINT UQ_INTERNACAO_ID_EXTERNO UNIQUE (INSTITUICAO,ID_EXTERNO);

/************************************************************************************************************/
-- CREATE INDEXS
/************************************************************************************************************/
CREATE INDEX IDX_CODIGO_DRG_CODIGO ON %s.CODIGO_DRG (CODIGO);

CREATE INDEX IDX_USUARIO_LOGIN ON %s.USUARIO (LOGIN);

CREATE INDEX IDX_PROCEDIMENTO_CODIGO ON %s.PROCEDIMENTO (CODIGO);

CREATE INDEX IDX_ESPECIALIDADE_NOME ON %s.ESPECIALIDADE (NOME);

CREATE INDEX IDX_INSTITUICAO_CODIGO ON %s.INSTITUICAO (CODIGO);

CREATE INDEX IDX_HOSPITAL_CODIGO ON %s.HOSPITAL (GRUPO,CODIGO);

CREATE INDEX IDX_INTERNACAO_DATA_ALTA ON %s.INTERNACAO (DATA_ALTA);

CREATE INDEX IDX_BENEFICIARIO_CODIGO_RN ON %s.BENEFICIARIO (GRUPO, CODIGO_PACIENTE, NOME, RECEM_NASCIDO);

CREATE INDEX IDX_INTERNACAO_ID_EXTERNO ON %s.INTERNACAO (INSTITUICAO,ID_EXTERNO);

CREATE INDEX IDX_INTERNACAO_MEDICO_RESPONSAVEL ON %s.INTERNACAO_MEDICO (RESPONSAVEL);

CREATE INDEX IDX_INTERNACAO_CID_PRINCIPAL ON %s.INTERNACAO (CID_PRINCIPAL);

CREATE INDEX IDX_INTERNACAO_INSTITUICAO ON %s.INTERNACAO (INSTITUICAO);

CREATE INDEX IDX_INTERNACAO_HOSPITAL ON %s.INTERNACAO (HOSPITAL);

CREATE INDEX IDX_INTERNACAO_ORIGEM_READMISSAO_30_DIAS ON %s.INTERNACAO (ORIGEM_READMISSAO_30_DIAS);

CREATE INDEX IDX_INTERNACAO_DRG_BRASIL ON %s.INTERNACAO (DRG_BRASIL);

CREATE INDEX IDX_INTERNACAO_CONDICAO_ADQUIRIDA_INTERNCAO ON %s.INTERNACAO_CONDICAO_ADQUIRIDA (INTERNACAO);

CREATE INDEX IDX_INTERNACAO_MEDICO_INTERNCAO ON %s.INTERNACAO_MEDICO (INTERNACAO);

CREATE INDEX IDX_INTERNACAO_PROCEDIMENTO_INTERNCAO ON %s.INTERNACAO_PROCEDIMENTO (INTERNACAO);

CREATE INDEX IDX_INTERNACAO_RECEM_NASCIDO_INTERNCAO ON %s.INTERNACAO_RECEM_NASCIDO (INTERNACAO);

/************************************************************************************************************/
-- CREATE FUNCIONS
/************************************************************************************************************/
CREATE OR REPLACE FUNCTION %s.NEWID() RETURNS uuid AS $$ SELECT md5(random()::text || clock_timestamp()::text)::uuid $$ LANGUAGE SQL;
