
CREATE TABLE %s.CONFIGURACAO_APLICACAO (
	AUTOID smallint NOT NULL,
	API_KEY varchar(256) NOT NULL,
	UPDATED_VERSION varchar(10)
);


ALTER TABLE %s.CONFIGURACAO_APLICACAO ADD CONSTRAINT PK_CONFIGURACAO_APLICACAO PRIMARY KEY (AUTOID);

