<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://jmjsistemas.github.io/ws/calculadora"
             xmlns:gp="http://jmjsistemas.github.io/ws/calculadora" name="integracaoEcWS" targetNamespace="http://jmjsistemas.github.io/ws/calculadora">
    <wsdl:types>
        <xsi:schema xmlns:tns="http://jmjsistemas.github.io/ws/calculadora"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                    xmlns="http://www.w3.org/2001/XMLSchema" xmlns:gp="http://jmjsistemas.github.io/ws/calculadora"
                    targetNamespace="http://jmjsistemas.github.io/ws/calculadora">
            <xsi:import namespace="http://jmjsistemas.github.io/ws/calculadora" schemaLocation="objectFactory.xsd"/>
        </xsi:schema>
    </wsdl:types>
    <message name="IntegracaoEcRequest">
        <part name="IntegracaoEcRequest" element="gp:integracaoEcWS"/>
    </message>
    <message name="IntegracaoEcResponse">
        <part name="IntegracaoEcResponse" element="gp:confirmacaoWS"/>
    </message>
    <message name="ErroInesperadoFault">
        <part name="ErroInesperadoFault" element="gp:erroInesperadoWS"/>
    </message>
    <portType name="IntegracaoEcPortType">
        <operation name="IntegracaoEcOperation">
            <input message="tns:IntegracaoEcRequest"/>
            <output message="tns:IntegracaoEcResponse"/>
            <fault name="ErroInesperadoFault" message="tns:ErroInesperadoFault"/>
        </operation>
    </portType>
    <binding name="IntegracaoEcBinding" type="tns:IntegracaoEcPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="IntegracaoEcOperation">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
            <fault name="ErroInesperadoFault">
                <soap:fault name="ErroInesperadoFault" use="literal"/>
            </fault>
        </operation>
    </binding>
    <service name="IntegracaoEc">
        <port name="IntegracaoEcPort" binding="tns:IntegracaoEcBinding">
            <soap:address location="https://jmjsistemas.github.io/ws/calculadora"/>
        </port>
    </service>
</definitions>